// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import "strconv"

/// How a UI is meant to show a buff's value; `showOutputValueInUI` in the SDE.
/// A resistance buff reads as -20% and shows as +20%, hence Inverted.
type DbuffDisplay int8

const (
	DbuffDisplayNormal   DbuffDisplay = 0
	DbuffDisplayInverted DbuffDisplay = 1
	DbuffDisplayHidden   DbuffDisplay = 2
)

var EnumNamesDbuffDisplay = map[DbuffDisplay]string{
	DbuffDisplayNormal:   "Normal",
	DbuffDisplayInverted: "Inverted",
	DbuffDisplayHidden:   "Hidden",
}

var EnumValuesDbuffDisplay = map[string]DbuffDisplay{
	"Normal":   DbuffDisplayNormal,
	"Inverted": DbuffDisplayInverted,
	"Hidden":   DbuffDisplayHidden,
}

func (v DbuffDisplay) String() string {
	if s, ok := EnumNamesDbuffDisplay[v]; ok {
		return s
	}
	return "DbuffDisplay(" + strconv.FormatInt(int64(v), 10) + ")"
}
