// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DbuffModifier struct {
	_tab flatbuffers.Struct
}

func (rcv *DbuffModifier) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DbuffModifier) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *DbuffModifier) Func() ModifierFunc {
	return ModifierFunc(rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(0)))
}
func (rcv *DbuffModifier) MutateFunc(n ModifierFunc) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(0), int8(n))
}

func (rcv *DbuffModifier) ModifiedAttributeId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *DbuffModifier) MutateModifiedAttributeId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *DbuffModifier) GroupId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *DbuffModifier) MutateGroupId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *DbuffModifier) SkillTypeId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *DbuffModifier) MutateSkillTypeId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func CreateDbuffModifier(builder *flatbuffers.Builder, func_ ModifierFunc, modifiedAttributeId int32, groupId int32, skillTypeId int32) flatbuffers.UOffsetT {
	builder.Prep(4, 16)
	builder.PrependInt32(skillTypeId)
	builder.PrependInt32(groupId)
	builder.PrependInt32(modifiedAttributeId)
	builder.Pad(3)
	builder.PrependInt8(int8(func_))
	return builder.Offset()
}
