// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DbuffCollection struct {
	_tab flatbuffers.Table
}

func GetRootAsDbuffCollection(buf []byte, offset flatbuffers.UOffsetT) *DbuffCollection {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DbuffCollection{}
	x.Init(buf, n+offset)
	return x
}

func FinishDbuffCollectionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDbuffCollection(buf []byte, offset flatbuffers.UOffsetT) *DbuffCollection {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DbuffCollection{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDbuffCollectionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DbuffCollection) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DbuffCollection) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DbuffCollection) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DbuffCollection) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func DbuffCollectionKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &DbuffCollection{}
	obj2 := &DbuffCollection{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return obj1.Id() < obj2.Id()
}

func (rcv *DbuffCollection) LookupByKey(key int32, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &DbuffCollection{}
		obj.Init(buf, tableOffset)
		val := obj.Id()
		comp := 0
		if val > key {
			comp = 1
		} else if val < key {
			comp = -1
		}
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *DbuffCollection) DisplayName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DbuffCollection) AggregateMode() DbuffAggregateMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return DbuffAggregateMode(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DbuffCollection) MutateAggregateMode(n DbuffAggregateMode) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *DbuffCollection) Operation() ModifierOperation {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return ModifierOperation(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DbuffCollection) MutateOperation(n ModifierOperation) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

func (rcv *DbuffCollection) Display() DbuffDisplay {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return DbuffDisplay(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DbuffCollection) MutateDisplay(n DbuffDisplay) bool {
	return rcv._tab.MutateInt8Slot(12, int8(n))
}

func (rcv *DbuffCollection) Modifiers(obj *DbuffModifier, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 16
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DbuffCollection) ModifiersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DbuffCollectionStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func DbuffCollectionAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func DbuffCollectionAddDisplayName(builder *flatbuffers.Builder, displayName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(displayName), 0)
}
func DbuffCollectionAddAggregateMode(builder *flatbuffers.Builder, aggregateMode DbuffAggregateMode) {
	builder.PrependInt8Slot(2, int8(aggregateMode), 0)
}
func DbuffCollectionAddOperation(builder *flatbuffers.Builder, operation ModifierOperation) {
	builder.PrependInt8Slot(3, int8(operation), 0)
}
func DbuffCollectionAddDisplay(builder *flatbuffers.Builder, display DbuffDisplay) {
	builder.PrependInt8Slot(4, int8(display), 0)
}
func DbuffCollectionAddModifiers(builder *flatbuffers.Builder, modifiers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(modifiers), 0)
}
func DbuffCollectionStartModifiersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(16, numElems, 4)
}
func DbuffCollectionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
