// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import "strconv"

type DbuffAggregateMode int8

const (
	DbuffAggregateModeMaximum DbuffAggregateMode = 0
	DbuffAggregateModeMinimum DbuffAggregateMode = 1
)

var EnumNamesDbuffAggregateMode = map[DbuffAggregateMode]string{
	DbuffAggregateModeMaximum: "Maximum",
	DbuffAggregateModeMinimum: "Minimum",
}

var EnumValuesDbuffAggregateMode = map[string]DbuffAggregateMode{
	"Maximum": DbuffAggregateModeMaximum,
	"Minimum": DbuffAggregateModeMinimum,
}

func (v DbuffAggregateMode) String() string {
	if s, ok := EnumNamesDbuffAggregateMode[v]; ok {
		return s
	}
	return "DbuffAggregateMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
