// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DogmaEffect struct {
	_tab flatbuffers.Table
}

func GetRootAsDogmaEffect(buf []byte, offset flatbuffers.UOffsetT) *DogmaEffect {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DogmaEffect{}
	x.Init(buf, n+offset)
	return x
}

func FinishDogmaEffectBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDogmaEffect(buf []byte, offset flatbuffers.UOffsetT) *DogmaEffect {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DogmaEffect{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDogmaEffectBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DogmaEffect) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DogmaEffect) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DogmaEffect) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaEffect) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func DogmaEffectKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &DogmaEffect{}
	obj2 := &DogmaEffect{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return obj1.Id() < obj2.Id()
}

func (rcv *DogmaEffect) LookupByKey(key int32, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &DogmaEffect{}
		obj.Init(buf, tableOffset)
		val := obj.Id()
		comp := 0
		if val > key {
			comp = 1
		} else if val < key {
			comp = -1
		}
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *DogmaEffect) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DogmaEffect) DisplayName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DogmaEffect) EffectCategory() EffectCategory {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return EffectCategory(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DogmaEffect) MutateEffectCategory(n EffectCategory) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

func (rcv *DogmaEffect) Published() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaEffect) MutatePublished(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *DogmaEffect) ElectronicChance() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaEffect) MutateElectronicChance(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *DogmaEffect) IsAssistance() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaEffect) MutateIsAssistance(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *DogmaEffect) IsOffensive() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaEffect) MutateIsOffensive(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *DogmaEffect) IsWarpSafe() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaEffect) MutateIsWarpSafe(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *DogmaEffect) PropulsionChance() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaEffect) MutatePropulsionChance(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *DogmaEffect) RangeChance() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaEffect) MutateRangeChance(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func (rcv *DogmaEffect) DisallowAutoRepeat() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaEffect) MutateDisallowAutoRepeat(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *DogmaEffect) DischargeAttributeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaEffect) MutateDischargeAttributeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(28, n)
}

func (rcv *DogmaEffect) DurationAttributeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaEffect) MutateDurationAttributeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(30, n)
}

func (rcv *DogmaEffect) FalloffAttributeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaEffect) MutateFalloffAttributeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(32, n)
}

func (rcv *DogmaEffect) FittingUsageChanceAttributeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaEffect) MutateFittingUsageChanceAttributeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(34, n)
}

func (rcv *DogmaEffect) RangeAttributeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaEffect) MutateRangeAttributeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(36, n)
}

func (rcv *DogmaEffect) ResistanceAttributeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaEffect) MutateResistanceAttributeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(38, n)
}

func (rcv *DogmaEffect) TrackingSpeedAttributeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaEffect) MutateTrackingSpeedAttributeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(40, n)
}

func (rcv *DogmaEffect) Modifiers(obj *Modifier, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 20
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DogmaEffect) ModifiersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DogmaEffectStart(builder *flatbuffers.Builder) {
	builder.StartObject(20)
}
func DogmaEffectAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func DogmaEffectAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func DogmaEffectAddDisplayName(builder *flatbuffers.Builder, displayName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(displayName), 0)
}
func DogmaEffectAddEffectCategory(builder *flatbuffers.Builder, effectCategory EffectCategory) {
	builder.PrependInt8Slot(3, int8(effectCategory), 0)
}
func DogmaEffectAddPublished(builder *flatbuffers.Builder, published bool) {
	builder.PrependBoolSlot(4, published, false)
}
func DogmaEffectAddElectronicChance(builder *flatbuffers.Builder, electronicChance bool) {
	builder.PrependBoolSlot(5, electronicChance, false)
}
func DogmaEffectAddIsAssistance(builder *flatbuffers.Builder, isAssistance bool) {
	builder.PrependBoolSlot(6, isAssistance, false)
}
func DogmaEffectAddIsOffensive(builder *flatbuffers.Builder, isOffensive bool) {
	builder.PrependBoolSlot(7, isOffensive, false)
}
func DogmaEffectAddIsWarpSafe(builder *flatbuffers.Builder, isWarpSafe bool) {
	builder.PrependBoolSlot(8, isWarpSafe, false)
}
func DogmaEffectAddPropulsionChance(builder *flatbuffers.Builder, propulsionChance bool) {
	builder.PrependBoolSlot(9, propulsionChance, false)
}
func DogmaEffectAddRangeChance(builder *flatbuffers.Builder, rangeChance bool) {
	builder.PrependBoolSlot(10, rangeChance, false)
}
func DogmaEffectAddDisallowAutoRepeat(builder *flatbuffers.Builder, disallowAutoRepeat bool) {
	builder.PrependBoolSlot(11, disallowAutoRepeat, false)
}
func DogmaEffectAddDischargeAttributeId(builder *flatbuffers.Builder, dischargeAttributeId int32) {
	builder.PrependInt32Slot(12, dischargeAttributeId, 0)
}
func DogmaEffectAddDurationAttributeId(builder *flatbuffers.Builder, durationAttributeId int32) {
	builder.PrependInt32Slot(13, durationAttributeId, 0)
}
func DogmaEffectAddFalloffAttributeId(builder *flatbuffers.Builder, falloffAttributeId int32) {
	builder.PrependInt32Slot(14, falloffAttributeId, 0)
}
func DogmaEffectAddFittingUsageChanceAttributeId(builder *flatbuffers.Builder, fittingUsageChanceAttributeId int32) {
	builder.PrependInt32Slot(15, fittingUsageChanceAttributeId, 0)
}
func DogmaEffectAddRangeAttributeId(builder *flatbuffers.Builder, rangeAttributeId int32) {
	builder.PrependInt32Slot(16, rangeAttributeId, 0)
}
func DogmaEffectAddResistanceAttributeId(builder *flatbuffers.Builder, resistanceAttributeId int32) {
	builder.PrependInt32Slot(17, resistanceAttributeId, 0)
}
func DogmaEffectAddTrackingSpeedAttributeId(builder *flatbuffers.Builder, trackingSpeedAttributeId int32) {
	builder.PrependInt32Slot(18, trackingSpeedAttributeId, 0)
}
func DogmaEffectAddModifiers(builder *flatbuffers.Builder, modifiers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(19, flatbuffers.UOffsetT(modifiers), 0)
}
func DogmaEffectStartModifiersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(20, numElems, 4)
}
func DogmaEffectEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
