// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DogmaAttributeCategory struct {
	_tab flatbuffers.Table
}

func GetRootAsDogmaAttributeCategory(buf []byte, offset flatbuffers.UOffsetT) *DogmaAttributeCategory {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DogmaAttributeCategory{}
	x.Init(buf, n+offset)
	return x
}

func FinishDogmaAttributeCategoryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDogmaAttributeCategory(buf []byte, offset flatbuffers.UOffsetT) *DogmaAttributeCategory {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DogmaAttributeCategory{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDogmaAttributeCategoryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DogmaAttributeCategory) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DogmaAttributeCategory) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DogmaAttributeCategory) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaAttributeCategory) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func DogmaAttributeCategoryKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &DogmaAttributeCategory{}
	obj2 := &DogmaAttributeCategory{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return obj1.Id() < obj2.Id()
}

func (rcv *DogmaAttributeCategory) LookupByKey(key int32, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &DogmaAttributeCategory{}
		obj.Init(buf, tableOffset)
		val := obj.Id()
		comp := 0
		if val > key {
			comp = 1
		} else if val < key {
			comp = -1
		}
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *DogmaAttributeCategory) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DogmaAttributeCategoryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DogmaAttributeCategoryAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func DogmaAttributeCategoryAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func DogmaAttributeCategoryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
