// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// What the client shows when hovering an attribute.
type DogmaAttributeText struct {
	_tab flatbuffers.Table
}

func GetRootAsDogmaAttributeText(buf []byte, offset flatbuffers.UOffsetT) *DogmaAttributeText {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DogmaAttributeText{}
	x.Init(buf, n+offset)
	return x
}

func FinishDogmaAttributeTextBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDogmaAttributeText(buf []byte, offset flatbuffers.UOffsetT) *DogmaAttributeText {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DogmaAttributeText{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDogmaAttributeTextBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DogmaAttributeText) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DogmaAttributeText) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DogmaAttributeText) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaAttributeText) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func DogmaAttributeTextKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &DogmaAttributeText{}
	obj2 := &DogmaAttributeText{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return obj1.Id() < obj2.Id()
}

func (rcv *DogmaAttributeText) LookupByKey(key int32, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &DogmaAttributeText{}
		obj.Init(buf, tableOffset)
		val := obj.Id()
		comp := 0
		if val > key {
			comp = 1
		} else if val < key {
			comp = -1
		}
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *DogmaAttributeText) TooltipTitle() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DogmaAttributeText) TooltipDescription() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DogmaAttributeTextStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DogmaAttributeTextAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func DogmaAttributeTextAddTooltipTitle(builder *flatbuffers.Builder, tooltipTitle flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(tooltipTitle), 0)
}
func DogmaAttributeTextAddTooltipDescription(builder *flatbuffers.Builder, tooltipDescription flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(tooltipDescription), 0)
}
func DogmaAttributeTextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
