// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DogmaAttribute struct {
	_tab flatbuffers.Table
}

func GetRootAsDogmaAttribute(buf []byte, offset flatbuffers.UOffsetT) *DogmaAttribute {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DogmaAttribute{}
	x.Init(buf, n+offset)
	return x
}

func FinishDogmaAttributeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDogmaAttribute(buf []byte, offset flatbuffers.UOffsetT) *DogmaAttribute {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DogmaAttribute{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDogmaAttributeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DogmaAttribute) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DogmaAttribute) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DogmaAttribute) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaAttribute) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func DogmaAttributeKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &DogmaAttribute{}
	obj2 := &DogmaAttribute{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return obj1.Id() < obj2.Id()
}

func (rcv *DogmaAttribute) LookupByKey(key int32, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &DogmaAttribute{}
		obj.Init(buf, tableOffset)
		val := obj.Id()
		comp := 0
		if val > key {
			comp = 1
		} else if val < key {
			comp = -1
		}
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *DogmaAttribute) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DogmaAttribute) DisplayName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DogmaAttribute) DefaultValue() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DogmaAttribute) MutateDefaultValue(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *DogmaAttribute) HighIsGood() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaAttribute) MutateHighIsGood(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *DogmaAttribute) Stackable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaAttribute) MutateStackable(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *DogmaAttribute) Published() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DogmaAttribute) MutatePublished(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *DogmaAttribute) UnitId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaAttribute) MutateUnitId(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func (rcv *DogmaAttribute) MinAttributeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaAttribute) MutateMinAttributeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(20, n)
}

func (rcv *DogmaAttribute) MaxAttributeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaAttribute) MutateMaxAttributeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(22, n)
}

func (rcv *DogmaAttribute) CategoryId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DogmaAttribute) MutateCategoryId(n int32) bool {
	return rcv._tab.MutateInt32Slot(24, n)
}

func DogmaAttributeStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func DogmaAttributeAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func DogmaAttributeAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func DogmaAttributeAddDisplayName(builder *flatbuffers.Builder, displayName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(displayName), 0)
}
func DogmaAttributeAddDefaultValue(builder *flatbuffers.Builder, defaultValue float32) {
	builder.PrependFloat32Slot(3, defaultValue, 0.0)
}
func DogmaAttributeAddHighIsGood(builder *flatbuffers.Builder, highIsGood bool) {
	builder.PrependBoolSlot(4, highIsGood, false)
}
func DogmaAttributeAddStackable(builder *flatbuffers.Builder, stackable bool) {
	builder.PrependBoolSlot(5, stackable, false)
}
func DogmaAttributeAddPublished(builder *flatbuffers.Builder, published bool) {
	builder.PrependBoolSlot(6, published, false)
}
func DogmaAttributeAddUnitId(builder *flatbuffers.Builder, unitId int32) {
	builder.PrependInt32Slot(7, unitId, 0)
}
func DogmaAttributeAddMinAttributeId(builder *flatbuffers.Builder, minAttributeId int32) {
	builder.PrependInt32Slot(8, minAttributeId, 0)
}
func DogmaAttributeAddMaxAttributeId(builder *flatbuffers.Builder, maxAttributeId int32) {
	builder.PrependInt32Slot(9, maxAttributeId, 0)
}
func DogmaAttributeAddCategoryId(builder *flatbuffers.Builder, categoryId int32) {
	builder.PrependInt32Slot(10, categoryId, 0)
}
func DogmaAttributeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
