// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import "strconv"

type EffectCategory int8

const (
	EffectCategoryPassive  EffectCategory = 0
	EffectCategoryActive   EffectCategory = 1
	EffectCategoryTarget   EffectCategory = 2
	EffectCategoryArea     EffectCategory = 3
	EffectCategoryOnline   EffectCategory = 4
	EffectCategoryOverload EffectCategory = 5
	EffectCategoryDungeon  EffectCategory = 6
	EffectCategorySystem   EffectCategory = 7
)

var EnumNamesEffectCategory = map[EffectCategory]string{
	EffectCategoryPassive:  "Passive",
	EffectCategoryActive:   "Active",
	EffectCategoryTarget:   "Target",
	EffectCategoryArea:     "Area",
	EffectCategoryOnline:   "Online",
	EffectCategoryOverload: "Overload",
	EffectCategoryDungeon:  "Dungeon",
	EffectCategorySystem:   "System",
}

var EnumValuesEffectCategory = map[string]EffectCategory{
	"Passive":  EffectCategoryPassive,
	"Active":   EffectCategoryActive,
	"Target":   EffectCategoryTarget,
	"Area":     EffectCategoryArea,
	"Online":   EffectCategoryOnline,
	"Overload": EffectCategoryOverload,
	"Dungeon":  EffectCategoryDungeon,
	"System":   EffectCategorySystem,
}

func (v EffectCategory) String() string {
	if s, ok := EnumNamesEffectCategory[v]; ok {
		return s
	}
	return "EffectCategory(" + strconv.FormatInt(int64(v), 10) + ")"
}
