// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FighterAbility struct {
	_tab flatbuffers.Table
}

func GetRootAsFighterAbility(buf []byte, offset flatbuffers.UOffsetT) *FighterAbility {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FighterAbility{}
	x.Init(buf, n+offset)
	return x
}

func FinishFighterAbilityBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFighterAbility(buf []byte, offset flatbuffers.UOffsetT) *FighterAbility {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FighterAbility{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFighterAbilityBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FighterAbility) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FighterAbility) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FighterAbility) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FighterAbility) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func FighterAbilityKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &FighterAbility{}
	obj2 := &FighterAbility{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return obj1.Id() < obj2.Id()
}

func (rcv *FighterAbility) LookupByKey(key int32, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &FighterAbility{}
		obj.Init(buf, tableOffset)
		val := obj.Id()
		comp := 0
		if val > key {
			comp = 1
		} else if val < key {
			comp = -1
		}
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *FighterAbility) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FighterAbility) EffectId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FighterAbility) MutateEffectId(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func FighterAbilityStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FighterAbilityAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func FighterAbilityAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func FighterAbilityAddEffectId(builder *flatbuffers.Builder, effectId int32) {
	builder.PrependInt32Slot(2, effectId, 0)
}
func FighterAbilityEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
