// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Modifier struct {
	_tab flatbuffers.Struct
}

func (rcv *Modifier) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Modifier) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Modifier) Domain() ModifierDomain {
	return ModifierDomain(rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(0)))
}
func (rcv *Modifier) MutateDomain(n ModifierDomain) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(0), int8(n))
}

func (rcv *Modifier) Func() ModifierFunc {
	return ModifierFunc(rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(1)))
}
func (rcv *Modifier) MutateFunc(n ModifierFunc) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(1), int8(n))
}

func (rcv *Modifier) Operation() ModifierOperation {
	return ModifierOperation(rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(2)))
}
func (rcv *Modifier) MutateOperation(n ModifierOperation) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(2), int8(n))
}

func (rcv *Modifier) ModifiedAttributeId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Modifier) MutateModifiedAttributeId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *Modifier) ModifyingAttributeId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Modifier) MutateModifyingAttributeId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *Modifier) GroupId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *Modifier) MutateGroupId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *Modifier) SkillTypeId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *Modifier) MutateSkillTypeId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func CreateModifier(builder *flatbuffers.Builder, domain ModifierDomain, func_ ModifierFunc, operation ModifierOperation, modifiedAttributeId int32, modifyingAttributeId int32, groupId int32, skillTypeId int32) flatbuffers.UOffsetT {
	builder.Prep(4, 20)
	builder.PrependInt32(skillTypeId)
	builder.PrependInt32(groupId)
	builder.PrependInt32(modifyingAttributeId)
	builder.PrependInt32(modifiedAttributeId)
	builder.Pad(1)
	builder.PrependInt8(int8(operation))
	builder.PrependInt8(int8(func_))
	builder.PrependInt8(int8(domain))
	return builder.Offset()
}
