// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import "strconv"

type ModifierOperation int8

const (
	ModifierOperationUnset       ModifierOperation = -2
	ModifierOperationPreAssign   ModifierOperation = -1
	ModifierOperationPreMul      ModifierOperation = 0
	ModifierOperationPreDiv      ModifierOperation = 1
	ModifierOperationModAdd      ModifierOperation = 2
	ModifierOperationModSub      ModifierOperation = 3
	ModifierOperationPostMul     ModifierOperation = 4
	ModifierOperationPostDiv     ModifierOperation = 5
	ModifierOperationPostPercent ModifierOperation = 6
	ModifierOperationPostAssign  ModifierOperation = 7
)

var EnumNamesModifierOperation = map[ModifierOperation]string{
	ModifierOperationUnset:       "Unset",
	ModifierOperationPreAssign:   "PreAssign",
	ModifierOperationPreMul:      "PreMul",
	ModifierOperationPreDiv:      "PreDiv",
	ModifierOperationModAdd:      "ModAdd",
	ModifierOperationModSub:      "ModSub",
	ModifierOperationPostMul:     "PostMul",
	ModifierOperationPostDiv:     "PostDiv",
	ModifierOperationPostPercent: "PostPercent",
	ModifierOperationPostAssign:  "PostAssign",
}

var EnumValuesModifierOperation = map[string]ModifierOperation{
	"Unset":       ModifierOperationUnset,
	"PreAssign":   ModifierOperationPreAssign,
	"PreMul":      ModifierOperationPreMul,
	"PreDiv":      ModifierOperationPreDiv,
	"ModAdd":      ModifierOperationModAdd,
	"ModSub":      ModifierOperationModSub,
	"PostMul":     ModifierOperationPostMul,
	"PostDiv":     ModifierOperationPostDiv,
	"PostPercent": ModifierOperationPostPercent,
	"PostAssign":  ModifierOperationPostAssign,
}

func (v ModifierOperation) String() string {
	if s, ok := EnumNamesModifierOperation[v]; ok {
		return s
	}
	return "ModifierOperation(" + strconv.FormatInt(int64(v), 10) + ")"
}
