// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import "strconv"

type ModifierDomain int8

const (
	ModifierDomainItemID      ModifierDomain = 0
	ModifierDomainShipID      ModifierDomain = 1
	ModifierDomainCharID      ModifierDomain = 2
	ModifierDomainOtherID     ModifierDomain = 3
	ModifierDomainStructureID ModifierDomain = 4
	ModifierDomainTarget      ModifierDomain = 5
	ModifierDomainTargetID    ModifierDomain = 6
)

var EnumNamesModifierDomain = map[ModifierDomain]string{
	ModifierDomainItemID:      "ItemID",
	ModifierDomainShipID:      "ShipID",
	ModifierDomainCharID:      "CharID",
	ModifierDomainOtherID:     "OtherID",
	ModifierDomainStructureID: "StructureID",
	ModifierDomainTarget:      "Target",
	ModifierDomainTargetID:    "TargetID",
}

var EnumValuesModifierDomain = map[string]ModifierDomain{
	"ItemID":      ModifierDomainItemID,
	"ShipID":      ModifierDomainShipID,
	"CharID":      ModifierDomainCharID,
	"OtherID":     ModifierDomainOtherID,
	"StructureID": ModifierDomainStructureID,
	"Target":      ModifierDomainTarget,
	"TargetID":    ModifierDomainTargetID,
}

func (v ModifierDomain) String() string {
	if s, ok := EnumNamesModifierDomain[v]; ok {
		return s
	}
	return "ModifierDomain(" + strconv.FormatInt(int64(v), 10) + ")"
}
