// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import "strconv"

type ModifierFunc int8

const (
	ModifierFuncItemModifier                  ModifierFunc = 0
	ModifierFuncLocationGroupModifier         ModifierFunc = 1
	ModifierFuncLocationModifier              ModifierFunc = 2
	ModifierFuncLocationRequiredSkillModifier ModifierFunc = 3
	ModifierFuncOwnerRequiredSkillModifier    ModifierFunc = 4
	ModifierFuncEffectStopper                 ModifierFunc = 5
)

var EnumNamesModifierFunc = map[ModifierFunc]string{
	ModifierFuncItemModifier:                  "ItemModifier",
	ModifierFuncLocationGroupModifier:         "LocationGroupModifier",
	ModifierFuncLocationModifier:              "LocationModifier",
	ModifierFuncLocationRequiredSkillModifier: "LocationRequiredSkillModifier",
	ModifierFuncOwnerRequiredSkillModifier:    "OwnerRequiredSkillModifier",
	ModifierFuncEffectStopper:                 "EffectStopper",
}

var EnumValuesModifierFunc = map[string]ModifierFunc{
	"ItemModifier":                  ModifierFuncItemModifier,
	"LocationGroupModifier":         ModifierFuncLocationGroupModifier,
	"LocationModifier":              ModifierFuncLocationModifier,
	"LocationRequiredSkillModifier": ModifierFuncLocationRequiredSkillModifier,
	"OwnerRequiredSkillModifier":    ModifierFuncOwnerRequiredSkillModifier,
	"EffectStopper":                 ModifierFuncEffectStopper,
}

func (v ModifierFunc) String() string {
	if s, ok := EnumNamesModifierFunc[v]; ok {
		return s
	}
	return "ModifierFunc(" + strconv.FormatInt(int64(v), 10) + ")"
}
