// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MutaplasmidMapping struct {
	_tab flatbuffers.Table
}

func GetRootAsMutaplasmidMapping(buf []byte, offset flatbuffers.UOffsetT) *MutaplasmidMapping {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MutaplasmidMapping{}
	x.Init(buf, n+offset)
	return x
}

func FinishMutaplasmidMappingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMutaplasmidMapping(buf []byte, offset flatbuffers.UOffsetT) *MutaplasmidMapping {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MutaplasmidMapping{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMutaplasmidMappingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MutaplasmidMapping) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MutaplasmidMapping) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MutaplasmidMapping) ApplicableTypeIds(j int) int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *MutaplasmidMapping) ApplicableTypeIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MutaplasmidMapping) MutateApplicableTypeIds(j int, n int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *MutaplasmidMapping) ResultingTypeId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MutaplasmidMapping) MutateResultingTypeId(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func MutaplasmidMappingStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MutaplasmidMappingAddApplicableTypeIds(builder *flatbuffers.Builder, applicableTypeIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(applicableTypeIds), 0)
}
func MutaplasmidMappingStartApplicableTypeIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MutaplasmidMappingAddResultingTypeId(builder *flatbuffers.Builder, resultingTypeId int32) {
	builder.PrependInt32Slot(1, resultingTypeId, 0)
}
func MutaplasmidMappingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
