// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MutaplasmidAttribute struct {
	_tab flatbuffers.Struct
}

func (rcv *MutaplasmidAttribute) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MutaplasmidAttribute) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *MutaplasmidAttribute) AttributeId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *MutaplasmidAttribute) MutateAttributeId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *MutaplasmidAttribute) Min() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *MutaplasmidAttribute) MutateMin(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *MutaplasmidAttribute) Max() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *MutaplasmidAttribute) MutateMax(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateMutaplasmidAttribute(builder *flatbuffers.Builder, attributeId int32, min float32, max float32) flatbuffers.UOffsetT {
	builder.Prep(4, 12)
	builder.PrependFloat32(max)
	builder.PrependFloat32(min)
	builder.PrependInt32(attributeId)
	return builder.Offset()
}
