// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Name lookup, in a file of its own.
///
/// An EFT-fit can be written in any of the eight languages EVE supports, so a
/// name has to be matchable back to a type.
type Names struct {
	_tab flatbuffers.Table
}

const NamesIdentifier = "ESFN"

func GetRootAsNames(buf []byte, offset flatbuffers.UOffsetT) *Names {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Names{}
	x.Init(buf, n+offset)
	return x
}

func FinishNamesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(NamesIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func NamesBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, NamesIdentifier)
}

func GetSizePrefixedRootAsNames(buf []byte, offset flatbuffers.UOffsetT) *Names {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Names{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNamesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(NamesIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedNamesBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, NamesIdentifier)
}

func (rcv *Names) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Names) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Names) BuildNumber() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Names) MutateBuildNumber(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

/// Every name of every type, in every language, lowercased and sorted by
/// UTF-8 bytes. Lowercasing is per code point and locale-independent, so
/// that a fit does not have to match the case.
func (rcv *Names) Names(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *Names) NamesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Every name of every type, in every language, lowercased and sorted by
/// UTF-8 bytes. Lowercasing is per code point and locale-independent, so
/// that a fit does not have to match the case.
func (rcv *Names) TypeIds(j int) int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *Names) TypeIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Names) MutateTypeIds(j int, n int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func NamesStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func NamesAddBuildNumber(builder *flatbuffers.Builder, buildNumber int32) {
	builder.PrependInt32Slot(0, buildNumber, 0)
}
func NamesAddNames(builder *flatbuffers.Builder, names flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(names), 0)
}
func NamesStartNamesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func NamesAddTypeIds(builder *flatbuffers.Builder, typeIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(typeIds), 0)
}
func NamesStartTypeIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func NamesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
