// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Texts struct {
	_tab flatbuffers.Table
}

const TextsIdentifier = "ESFT"

func GetRootAsTexts(buf []byte, offset flatbuffers.UOffsetT) *Texts {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Texts{}
	x.Init(buf, n+offset)
	return x
}

func FinishTextsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(TextsIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func TextsBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, TextsIdentifier)
}

func GetSizePrefixedRootAsTexts(buf []byte, offset flatbuffers.UOffsetT) *Texts {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Texts{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTextsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(TextsIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedTextsBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, TextsIdentifier)
}

func (rcv *Texts) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Texts) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Texts) BuildNumber() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Texts) MutateBuildNumber(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Texts) DogmaAttributes(obj *DogmaAttributeText, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Texts) DogmaAttributesByKey(obj *DogmaAttributeText, key int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		return obj.LookupByKey(key, x, rcv._tab.Bytes)
	}
	return false
}

func (rcv *Texts) DogmaAttributesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// When CCP released this SDE build, in seconds since the Unix epoch.
func (rcv *Texts) ReleaseDate() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

/// When CCP released this SDE build, in seconds since the Unix epoch.
func (rcv *Texts) MutateReleaseDate(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func TextsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TextsAddBuildNumber(builder *flatbuffers.Builder, buildNumber int32) {
	builder.PrependInt32Slot(0, buildNumber, 0)
}
func TextsAddDogmaAttributes(builder *flatbuffers.Builder, dogmaAttributes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(dogmaAttributes), 0)
}
func TextsStartDogmaAttributesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TextsAddReleaseDate(builder *flatbuffers.Builder, releaseDate int64) {
	builder.PrependInt64Slot(2, releaseDate, 0)
}
func TextsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
