// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TypeFighterAbility struct {
	_tab flatbuffers.Struct
}

func (rcv *TypeFighterAbility) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypeFighterAbility) Table() flatbuffers.Table {
	return rcv._tab.Table
}

/// The position in the fighter's ability bar, starting at 0.
func (rcv *TypeFighterAbility) Slot() int8 {
	return rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
/// The position in the fighter's ability bar, starting at 0.
func (rcv *TypeFighterAbility) MutateSlot(n int8) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TypeFighterAbility) AbilityId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *TypeFighterAbility) MutateAbilityId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

/// 0 when the ability has no cooldown.
func (rcv *TypeFighterAbility) CooldownSeconds() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
/// 0 when the ability has no cooldown.
func (rcv *TypeFighterAbility) MutateCooldownSeconds(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

/// 0 when the ability does not run out of charges.
func (rcv *TypeFighterAbility) ChargeCount() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
/// 0 when the ability does not run out of charges.
func (rcv *TypeFighterAbility) MutateChargeCount(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *TypeFighterAbility) RearmTimeSeconds() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *TypeFighterAbility) MutateRearmTimeSeconds(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func CreateTypeFighterAbility(builder *flatbuffers.Builder, slot int8, abilityId int32, cooldownSeconds float32, chargeCount int32, rearmTimeSeconds float32) flatbuffers.UOffsetT {
	builder.Prep(4, 20)
	builder.PrependFloat32(rearmTimeSeconds)
	builder.PrependInt32(chargeCount)
	builder.PrependFloat32(cooldownSeconds)
	builder.PrependInt32(abilityId)
	builder.Pad(3)
	builder.PrependInt8(slot)
	return builder.Offset()
}
