// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Type struct {
	_tab flatbuffers.Table
}

func GetRootAsType(buf []byte, offset flatbuffers.UOffsetT) *Type {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Type{}
	x.Init(buf, n+offset)
	return x
}

func FinishTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsType(buf []byte, offset flatbuffers.UOffsetT) *Type {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Type{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Type) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Type) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Type) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Type) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func TypeKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &Type{}
	obj2 := &Type{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return obj1.Id() < obj2.Id()
}

func (rcv *Type) LookupByKey(key int32, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &Type{}
		obj.Init(buf, tableOffset)
		val := obj.Id()
		comp := 0
		if val > key {
			comp = 1
		} else if val < key {
			comp = -1
		}
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

/// English. The other languages live in the Names file.
func (rcv *Type) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// English. The other languages live in the Names file.
func (rcv *Type) GroupId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Type) MutateGroupId(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *Type) CategoryId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Type) MutateCategoryId(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *Type) Published() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Type) MutatePublished(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *Type) FactionId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Type) MutateFactionId(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *Type) MarketGroupId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Type) MutateMarketGroupId(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *Type) MetaGroupId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Type) MutateMetaGroupId(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func (rcv *Type) RaceId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Type) MutateRaceId(n int32) bool {
	return rcv._tab.MutateInt32Slot(20, n)
}

func (rcv *Type) Capacity() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Type) MutateCapacity(n float32) bool {
	return rcv._tab.MutateFloat32Slot(22, n)
}

func (rcv *Type) Mass() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Type) MutateMass(n float32) bool {
	return rcv._tab.MutateFloat32Slot(24, n)
}

func (rcv *Type) Radius() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Type) MutateRadius(n float32) bool {
	return rcv._tab.MutateFloat32Slot(26, n)
}

func (rcv *Type) Volume() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *Type) MutateVolume(n float32) bool {
	return rcv._tab.MutateFloat32Slot(28, n)
}

func (rcv *Type) DogmaAttributes(obj *TypeDogmaAttribute, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 8
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Type) DogmaAttributesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Type) DogmaEffects(obj *TypeDogmaEffect, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 8
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Type) DogmaEffectsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Type) FighterAbilities(obj *TypeFighterAbility, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 20
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Type) FighterAbilitiesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(16)
}
func TypeAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func TypeAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func TypeAddGroupId(builder *flatbuffers.Builder, groupId int32) {
	builder.PrependInt32Slot(2, groupId, 0)
}
func TypeAddCategoryId(builder *flatbuffers.Builder, categoryId int32) {
	builder.PrependInt32Slot(3, categoryId, 0)
}
func TypeAddPublished(builder *flatbuffers.Builder, published bool) {
	builder.PrependBoolSlot(4, published, false)
}
func TypeAddFactionId(builder *flatbuffers.Builder, factionId int32) {
	builder.PrependInt32Slot(5, factionId, 0)
}
func TypeAddMarketGroupId(builder *flatbuffers.Builder, marketGroupId int32) {
	builder.PrependInt32Slot(6, marketGroupId, 0)
}
func TypeAddMetaGroupId(builder *flatbuffers.Builder, metaGroupId int32) {
	builder.PrependInt32Slot(7, metaGroupId, 0)
}
func TypeAddRaceId(builder *flatbuffers.Builder, raceId int32) {
	builder.PrependInt32Slot(8, raceId, 0)
}
func TypeAddCapacity(builder *flatbuffers.Builder, capacity float32) {
	builder.PrependFloat32(capacity)
	builder.Slot(9)
}
func TypeAddMass(builder *flatbuffers.Builder, mass float32) {
	builder.PrependFloat32(mass)
	builder.Slot(10)
}
func TypeAddRadius(builder *flatbuffers.Builder, radius float32) {
	builder.PrependFloat32(radius)
	builder.Slot(11)
}
func TypeAddVolume(builder *flatbuffers.Builder, volume float32) {
	builder.PrependFloat32(volume)
	builder.Slot(12)
}
func TypeAddDogmaAttributes(builder *flatbuffers.Builder, dogmaAttributes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(dogmaAttributes), 0)
}
func TypeStartDogmaAttributesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 4)
}
func TypeAddDogmaEffects(builder *flatbuffers.Builder, dogmaEffects flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(dogmaEffects), 0)
}
func TypeStartDogmaEffectsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 4)
}
func TypeAddFighterAbilities(builder *flatbuffers.Builder, fighterAbilities flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(15, flatbuffers.UOffsetT(fighterAbilities), 0)
}
func TypeStartFighterAbilitiesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(20, numElems, 4)
}
func TypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
