// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TypeDogmaAttribute struct {
	_tab flatbuffers.Struct
}

func (rcv *TypeDogmaAttribute) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypeDogmaAttribute) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TypeDogmaAttribute) AttributeId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TypeDogmaAttribute) MutateAttributeId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TypeDogmaAttribute) Value() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *TypeDogmaAttribute) MutateValue(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateTypeDogmaAttribute(builder *flatbuffers.Builder, attributeId int32, value float32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependFloat32(value)
	builder.PrependInt32(attributeId)
	return builder.Offset()
}
