// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TypeDogmaEffect struct {
	_tab flatbuffers.Struct
}

func (rcv *TypeDogmaEffect) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypeDogmaEffect) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TypeDogmaEffect) EffectId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TypeDogmaEffect) MutateEffectId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TypeDogmaEffect) IsDefault() bool {
	return rcv._tab.GetBool(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *TypeDogmaEffect) MutateIsDefault(n bool) bool {
	return rcv._tab.MutateBool(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateTypeDogmaEffect(builder *flatbuffers.Builder, effectId int32, isDefault bool) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.Pad(3)
	builder.PrependBool(isDefault)
	builder.PrependInt32(effectId)
	return builder.Offset()
}
