// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eve

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UnixTimestamp struct {
	_tab flatbuffers.Struct
}

func (rcv *UnixTimestamp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnixTimestamp) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *UnixTimestamp) Seconds() int64 {
	return rcv._tab.GetInt64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *UnixTimestamp) MutateSeconds(n int64) bool {
	return rcv._tab.MutateInt64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateUnixTimestamp(builder *flatbuffers.Builder, seconds int64) flatbuffers.UOffsetT {
	builder.Prep(8, 8)
	builder.PrependInt64(seconds)
	return builder.Offset()
}
